.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH DELPHI-RMBG 1  "delphitools-cli 0.1.0" "delphitools manual"
.SH NAME
rmbg \- Remove background from an image
.SH SYNOPSIS
\fBrmbg\fR [\fB\-h\fR|\fB\-\-help\fR] [\fIIMAGES\fR] 
.SH DESCRIPTION
Remove background from an image
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fIIMAGES\fR]

